kind: Pod
apiVersion: v1
metadata:
  name: p1
spec:
  containers:
    - name: p1
      image: jjong2/all:latest
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        limits:
         cpu: 1000m # 10m, 20m, ... 1000m
  #nodeSelector:
    # key: orin, ubuntu
  restartPolicy: Never
